show=drun
width=600
height=400
prompt=
location=center
normal_window=false
allow_images=true
allow_markup=true
matching=fuzzy
insensitive=true
gtk_dark=true
hide_scroll=true
sort_order=alphabetical
image_size=24
layer=overlay
